"""Response schemas for quote APIs in the provider backend."""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field


class QuoteSelectedAddOnResponse(BaseModel):
    """Represents one selected add-on returned in a provider quote response.

    Attributes:
        name: Selected add-on name.
        price: Selected add-on price.
    """

    name: str = Field(..., description="Selected add-on name")
    price: float = Field(..., ge=0, description="Selected add-on price")

    model_config = ConfigDict(extra="forbid")


class QuoteAvailableAddOnResponse(BaseModel):
    """Represents one available add-on returned in a provider quote response.

    Attributes:
        name: Available add-on name.
        description: Available add-on description.
        price: Available add-on price.
    """

    name: str = Field(..., description="Available add-on name")
    description: str = Field(..., description="Available add-on description")
    price: float = Field(..., ge=0, description="Available add-on price")

    model_config = ConfigDict(extra="forbid")


class QuoteItemResponse(BaseModel):
    """Represents one quote item generated by the provider backend.

    Attributes:
        plan_id: Provider plan identifier.
        company_name: Provider company name.
        logo_url: Optional provider logo URL.
        plan_name: Quoted plan name.
        coverage_amount: Quoted coverage amount.
        base_premium: Quoted base premium.
        duration_years: Quoted duration in years.
        benefits: Quoted benefits.
        available_add_ons: Add-ons available for the quoted plan.
        selected_add_ons: Selected add-ons for the quote item.
        add_on_total: Total add-on amount.
        tax_amount: Tax amount for the quote item.
        total_premium: Final total premium.
        quote_status: Current quote item status.
    """

    plan_id: str = Field(..., description="Provider plan identifier")
    company_name: str = Field(..., description="Provider company name")
    logo_url: str | None = Field(default=None, description="Optional provider logo URL")
    plan_name: str = Field(..., description="Quoted plan name")
    coverage_amount: float = Field(..., ge=0, description="Quoted coverage amount")
    base_premium: float = Field(..., ge=0, description="Quoted base premium")
    duration_years: int = Field(..., ge=1, description="Quoted duration in years")
    benefits: list[str] = Field(default_factory=list, description="Quoted benefits")
    available_add_ons: list[QuoteAvailableAddOnResponse] = Field(
        default_factory=list,
        description="Add-ons available for the quoted plan",
    )
    selected_add_ons: list[QuoteSelectedAddOnResponse] = Field(
        default_factory=list,
        description="Selected add-ons for the quote item",
    )
    add_on_total: float = Field(..., ge=0, description="Total add-on amount")
    tax_amount: float = Field(..., ge=0, description="Tax amount for the quote item")
    total_premium: float = Field(..., ge=0, description="Final total premium")
    quote_status: str = Field(..., description="Current quote item status")

    model_config = ConfigDict(extra="forbid")


class QuoteResponse(BaseModel):
    """Represents all generated quotes for a transaction.

    Attributes:
        transaction_id: Transaction identifier.
        selected_plan_id: Currently selected provider plan identifier.
        items: Generated quote items.
        created_at: Quote creation timestamp.
        updated_at: Quote last-update timestamp.
    """

    transaction_id: str = Field(..., description="Transaction identifier")
    selected_plan_id: str | None = Field(
        default=None,
        description="Currently selected provider plan identifier",
    )
    items: list[QuoteItemResponse] = Field(default_factory=list, description="Generated quote items")
    created_at: datetime = Field(..., description="Quote creation timestamp")
    updated_at: datetime = Field(..., description="Quote last-update timestamp")

    model_config = ConfigDict(extra="forbid")


class QuoteListResponse(BaseModel):
    """Represents a list of quote documents returned to the provider admin.

    Attributes:
        items: Returned quote documents.
        total_count: Total number of returned quote documents.
    """

    items: list[QuoteResponse] = Field(
        default_factory=list,
        description="Returned quote documents",
    )
    total_count: int = Field(..., ge=0, description="Total number of returned quotes")

    model_config = ConfigDict(extra="forbid")
