"""Insurance form submission and quote retrieval tools for the InsureFlow MCP server.

Covers:
- submit_insurance_form : Start a new insurance journey (no auth required)
- get_quotes           : Retrieve provider-generated quotes for a transaction
"""

from __future__ import annotations

import httpx

from config import MAIN_BACKEND_URL


async def submit_insurance_form(
    mobile_number: str,
    insurance_type: str,
    proposer_first_name: str,
    proposer_last_name: str,
    sum_insured_requested: float,
    policy_term_years: int,
    proposer_dob: str | None = None,
    proposer_email: str | None = None,
    proposer_gender: str | None = None,
    occupation: str | None = None,
    annual_income: float | None = None,
    city: str | None = None,
    state: str | None = None,
    postal_code: str | None = None,
) -> dict:
    """Submit a new insurance details form to start the customer journey.

    No authentication is required. The backend automatically creates or
    finds a user by mobile number, creates a transaction, and triggers
    quote generation from the provider backend.

    Args:
        mobile_number: Customer's mobile number (minimum 10 digits).
        insurance_type: Type of insurance (e.g. HEALTH, LIFE, MOTOR).
        proposer_first_name: Customer's first name.
        proposer_last_name: Customer's last name.
        sum_insured_requested: Coverage amount requested by the customer.
        policy_term_years: Requested policy duration in years (minimum 1).
        proposer_dob: Optional date of birth in YYYY-MM-DD format.
        proposer_email: Optional email address.
        proposer_gender: Optional gender value.
        occupation: Optional occupation for quote calculation.
        annual_income: Optional annual income for quote calculation.
        city: Optional city.
        state: Optional state.
        postal_code: Optional postal code.

    Returns:
        dict containing user_id, transaction_id, insurance_detail_id,
        current_status, and form_step.

    Raises:
        Exception: If the backend returns an error or is unreachable.
    """

    payload: dict = {
        "mobile_number": mobile_number,
        "insurance_type": insurance_type,
        "proposer_first_name": proposer_first_name,
        "proposer_last_name": proposer_last_name,
        "sum_insured_requested": sum_insured_requested,
        "policy_term_years": policy_term_years,
        "is_form_completed": True,
    }

    if proposer_dob:
        payload["proposer_dob"] = proposer_dob
    if proposer_email:
        payload["proposer_email"] = proposer_email
    if proposer_gender:
        payload["proposer_gender"] = proposer_gender
    if occupation:
        payload["occupation"] = occupation
    if annual_income is not None:
        payload["annual_income"] = annual_income
    if city:
        payload["city"] = city
    if state:
        payload["state"] = state
    if postal_code:
        payload["postal_code"] = postal_code

    async with httpx.AsyncClient() as client:
        response = await client.post(
            f"{MAIN_BACKEND_URL}/v1/insurance-details",
            json=payload,
            timeout=30.0,
        )

    if response.status_code not in (200, 201):
        raise Exception(
            f"Failed to submit insurance form. "
            f"Status: {response.status_code}. Detail: {response.text}"
        )

    return response.json()


async def get_quotes(transaction_id: str) -> dict:
    """Retrieve insurance quotes generated for a transaction.

    The quotes are generated by the provider backend during form submission.
    Each quote item contains plan details, base premium, add-ons, and
    total premium.

    Args:
        transaction_id: The transaction identifier returned after form submission.

    Returns:
        dict containing transaction_id, selected_plan_id, and a list of
        quote items (each with plan_id, company_name, plan_name,
        coverage_amount, base_premium, available_add_ons, total_premium, etc.)

    Raises:
        Exception: If the backend returns an error or is unreachable.
    """

    async with httpx.AsyncClient() as client:
        response = await client.get(
            f"{MAIN_BACKEND_URL}/v1/quotes/{transaction_id}",
            timeout=30.0,
        )

    if response.status_code != 200:
        raise Exception(
            f"Failed to fetch quotes for transaction {transaction_id}. "
            f"Status: {response.status_code}. Detail: {response.text}"
        )

    return response.json()
